=head1 NAME

Alleg::Squadroster - squad roster helper functions

=head2 VERSION

1.01 - updated for ACSS

0.01 - initial version (ASGS)

=head2 DEPENDENCIES

Depends on the accessibility and availability of https://acss.alleg.net/Stats/SquadRoster.aspx

=head2 SYNOPSIS

  use Alleg::Squadroster;
  
  my @squads = Squadroster::list_squads;
  print "squads: @squads\n";
  
  my $inactives = Squadroster::list_inactive("System X");
  print "@$inactives";

=head2 EXPORTED FUNCTIONS

	list_squads() - returns a @list currently active squads.

	list_inactive($squad) - list all inactive pilots in $squad

	list_leadership($squad) - list all pilots in $squad with a token (* or ^ or +) in an $arrayref
